changelog:
  exclude:
    labels:
      - duplicate
      - question
      - invalid
      - wontfix
    authors:
      - renovate[bot]
      - dependabot[bot]
  categories:
    - title: '🚀 Features'
      labels:
        - feature
        - enhancement
    - title: '🐛 Bug Fixes'
      labels:
        - bug
        - fix
        - hotfix
    - title: '⚡ Performance'
      labels:
        - performance
    - title: '🛡️ Security'
      labels:
        - security
    - title: '🧰 Maintenance & Chore'
      labels:
        - chore
        - documentation
        - dependencies
        - refactor
